name: Push to Azure

on: [push, delete, pull_request]

permissions:
  contents: read

jobs:
  to_azure:                                        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@ssh.dev.azure.com:v3/Ecoleshill/CSCN73030-F22/Attendance
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
