# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/CSCN73030-projectv-group9/Attendance.git"
          destination_repo: "git@ssh.dev.azure.com:v3/Ecoleshill/CSCN73030-F22/Attendance"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
